### ISSUE TITLE
Multiple mirror point option

### ISSUE THREAD

**Issue by mattcovo** [TobKra96/music_led_strip_control#103]
Hi,
awesome code! 
I'd like to ask you to add an option to set the ''mirror'' option to more than 2 pieces, for example I'm working on a 30 led stripes installed as a multi-point star and having issue to configure them properly.

I've temporarily edited the code /libs/effects/file..... to have this effect (see attachment)

![Unknown](https://user-images.githubusercontent.com/5131468/114226208-93822200-9973-11eb-8df5-dca9733ccc0e.jpeg)

**Comment by TobKra96** [comment]
Hey,

this very special and complicated to implement.
Have you thought about a wire/hardware solution. Share one data signal to all led strips parallel, so the will always mirror.

Have a great day.
TobKra
