### ISSUE TITLE
System Info page

### ISSUE THREAD

**Issue by TobKra96** [TobKra96/music_led_strip_control#114]
Add a page that polls data like:

- CPU
- RAM
- Network usage
- Temperatures
- Running Services
- hostapd service status

Maybe you can restart hostapd.

**Comment by Teraskull** [comment]
For CPU, RAM and Network Usage we can use [psutil](https://pypi.org/project/psutil/).

For Temperature we should use the dedicated software for raspberry pi:
```shell
/opt/vc/bin/vcgencmd measure_temp
```
Which in Python can be used like this:
```python
import os
import time


def measure_temp():
    temp = os.popen("vcgencmd measure_temp").readline()
    return (temp.replace("temp=",""))


print(measure_temp())
```

Getting running services and hostapd status can be done with `os` or `subprocess`.

**Comment by Teraskull** [comment]
Here is a good Flask example: https://github.com/Jahaja/psdash

**Comment by TobKra96** [comment]
API Implementation started: https://github.com/TobKra96/music_led_strip_control/commit/95557c85e42b3f8f75846906cfea4b6503131ac5 😎 

Added GetSystemInfoPerformance, GetSystemInfoTemperature, GetSystemInfoServices Endpoints


![image](https://user-images.githubusercontent.com/7833146/115928406-53986000-a486-11eb-9202-8774adc51374.png)

**Comment by TobKra96** [comment]
done with 2.2
