### ISSUE TITLE
Can I use any Linux distro as MLSC server?

### ISSUE THREAD

**Issue by dotnetaddicted** [TobKra96/music_led_strip_control#118]
Are there any reason to stick to Raspberry PI (device and OS) only when serving LED-strips via ESP8266 clients?
Isn't it possible to run MLSC server at laptop under Debian distro for example?
Thanks.

**Comment by TobKra96** [comment]
Hi, yes this should work. I do not see any limitations, but I haven't tried it yet.

**Comment by TobKra96** [comment]
done
