### ISSUE TITLE
Is it possible to change effects without use of web interface?

### ISSUE THREAD

**Issue by beardfacefacebeard** [TobKra96/music_led_strip_control#126]
i have everything running and it all works quite well. the effects are amazing.. but when i implement this into the project i am working on the rpi will not have internet access at all and will operate headless. 
im not really much for coding but i can do some simple things.. i was hoping to be able to cycle through effects with a tactile button press or a rotary switch if possible. im not sure if this can be easily attained or not, and if not that is ok. 
thanks for your time, and i appreciate all the work that has already been put into this. it is truly fantastic.

also, noting that this isnt really an issue i just wasnt sure how else to contact/question this. sorry if its not the proper way to go about things.

i just saw this https://github.com/TobKra96/music_led_strip_control/issues/94 and i am wondering if this is the same idea.. sorry for a duplicate question

**Comment by Teraskull** [comment]
Hi, yes, #94 is the correct way to access the API to control lights without the interface. We recently changed the API endpoint names in branch `dev_2.2`, but the idea is the same.

**Comment by beardfacefacebeard** [comment]
thanks for the response. follow up question, if i have multiple led devices (ie MainLED, SecondLED) and only want to address the change in one how would i vary that?
`SetActiveEffectForAll` is obviously going to change them all, would i use `SetActiveEffectForMainLED` -- using python

**Comment by Teraskull** [comment]
@beardfacefacebeard Check out our `dev_2.2` branch, there is a complete API documentation with examples. To be able to select a specific device, you should pass the device id as a query, like here:

![image](https://user-images.githubusercontent.com/24798198/120913684-1c2ded80-c699-11eb-876c-28ea30edbd56.png)


Also I strongly suggest to build your scripts with the new API endpoints, since the ones in `main` branch will not be backwards compatible after the new release.

**Comment by beardfacefacebeard** [comment]
im really sorry for my ignorance but i have no idea where that is. im fairly new to github and cant find the documentation youre referring to. i feel completely lost. i appreciate your patience

**Comment by Teraskull** [comment]
@beardfacefacebeard In the branch selector, choose `dev_2.2` and install that version.

![image](https://user-images.githubusercontent.com/24798198/120934349-4cf43e00-c6fe-11eb-8d6a-4f043075d46b.png)

**Comment by beardfacefacebeard** [comment]
oh, no wonder i was so lost.. thank you. this really is some amazing stuff. i appreciate it all so much.
