### ISSUE TITLE
NodeMCU Client SK6812 strip not supported?

### ISSUE THREAD

**Issue by TimoS911** [TobKra96/music_led_strip_control#127]
Hello,
just tested my 2nd room setup with a nodemcu on some SK6812 LED stip.

Got the nodemcu working over an existing network to my raspberry pi.
I can change effects and the stip lights in different ways.
BUT for example the single LED effect is showing incorrect. First LED B second is R third is G fourth is B and so on.

I think the problem is that the SK6812 LED stip needs the empty bits for the white channel to function properly.
If i change the device settings at the webinterface nothing changes at the LED strip.

Is it possible to fix this so i can use the SK6812RGBWW strips i got with that nodemcu?

-Timo

**Comment by TobKra96** [comment]
This bug should be fixed with the next version. 2.2
