### ISSUE TITLE
Setup question: aux speaker ouput (from another device) to raspberry pi

### ISSUE THREAD

**Issue by Marshalldog** [TobKra96/music_led_strip_control#165]
Hi
Is there a way to get the raspberry pi to listen to a speaker aux output (of a chrome cast with an HDMI to aux adapter) instead of a microphone?

**Comment by carlyd95** [comment]
Yes, use a usb soundcard.

https://www.amazon.com/Sabrent-External-Adapter-Windows-AU-MMSA/dp/B00IRVQ0F8/ref=mp_s_a_1_3?crid=14ZZOV5WE2SW5&keywords=usb+sound+card&qid=1654437329&sprefix=usb+aoundcard%2Caps%2C68&sr=8-3
