### ISSUE TITLE
Can't use RPI audio receiver (Bluetooth)

### ISSUE THREAD

**Issue by Xitee1** [TobKra96/music_led_strip_control#166]
I have installed MLSC on my Raspberry Pi with this https://github.com/nicokaiser/rpi-audio-receiver programm so I can send the data with Bluetooth to the RPi. I have selected the "microphone" (BL audio).
I have a ESP8266 with WLED connected with MLSC which is working just fine with the Non-Music effects.
However if I want a Music-Effect the connection to WLED times out (I think - the light pauses and stays on for a few seconds until it goes off and WLED is no longer saying that it is used through the API).
Can anyone help me?

![grafik](https://user-images.githubusercontent.com/59659167/172192808-20186364-e90d-4368-83c0-43944f14f2f8.png)

**Comment by TobKra96** [comment]
Hi,

looks like an issue with pyaudio and your music/input source. Does this error occurs, if you use the default device?

**Comment by FloKTC** [comment]
i have the same problem ( with the pi3) i try to config a virtual mic at the moment  , unfortunately unsuccessful so far

**Comment by TobKra96** [comment]
Yes, virtual mics are hard to config and buggy at the moment. At the moment I could not find a solution for virtual mics.
