### ISSUE TITLE
Host wifi server on wlan1. Possible?

### ISSUE THREAD

**Issue by toreupfeet** [TobKra96/music_led_strip_control#179]
Would it be possible to add a USB wifi card to the Pi4 and stay on the home network on wlan0 while hosting the MLSC server to ESP8266 clients on wlan1? Or vice versa?

Edit:

I did some googling and I believe this is indeed possible. Would someone please provide instructions as to how to do so? I have [one of these](https://www.amazon.com/gp/product/B00JDVRCI0) for my wlan1.

**Comment by TobKra96** [comment]
yes, this should be possible. Just configure one of the wifi as a normal client and the other one as an access point.
