### ISSUE TITLE
Firefox cant change settings

### ISSUE THREAD

**Issue by skyzonemc** [TobKra96/music_led_strip_control#18]
Can't change settings in Firefox, but Chrome works fine. Would be nice if fixed :)

**Comment by TobKra96** [comment]
Hi, can confirm the issue. The submit button reloads the page before the ajax package was sent.
Fixed by changing the type of the submit button to button. Thanks for reporting it. In the development, I always used Chrome :) . Have fun with the software.

Greeting Tobkra
