### ISSUE TITLE
possible to activate effect_random_cycle through api?

### ISSUE THREAD

**Issue by ahsu-2019** [TobKra96/music_led_strip_control#180]
Seems to only be activated via button, is api call possible?

**Comment by Teraskull** [comment]
Hi @ahsu-2019,

In branch `dev_2.3` the whole random cycle implementation was remade, you can now pass the effect `effect_random_cycle` through the API, just like the other effects.

The new implementation works in the backend, which allows to enable the random cycle for multiple devices, and have separate settings for each device.
