### ISSUE TITLE
Support for apa102/apa102c

### ISSUE THREAD

**Issue by ex0nuss** [TobKra96/music_led_strip_control#184]
Hi there,
I found some old APA102c LEDs lying around from an old home assistant project.
Is it possible to support them, since most libraries usually do? 

Cheers!

**Comment by TobKra96** [comment]
Hi,
we are using the following lib for the communication between the python script and the led strips.
https://github.com/jgarff/rpi_ws281x

As far as I can see, they do not support this kind of strip.
