### ISSUE TITLE
Run as Docker image

### ISSUE THREAD

**Issue by BjoernRave** [TobKra96/music_led_strip_control#187]
Has anybody had success running it inside a docker container?

**Comment by Teraskull** [comment]
Hi,
I tried building an image, but no success.
It depends on too many low level hardware points, that the only stable way to run it is directly.
Also there is no actual reason to use Docker here since a Python Environment is enough.

**Comment by BjoernRave** [comment]
I want to run it on my home server, where I try to run everything in a container, but I guess I will have to make an exeption then :)
