### ISSUE TITLE
Does this support 1gb ram rasp pis?

### ISSUE THREAD

**Issue by ignotus321** [TobKra96/music_led_strip_control#198]
For 1gb ram raspberry pi 4. Would it be compatible?

**Comment by Teraskull** [comment]
Yes, as you can see here, minimum 500mb of RAM is required:
	
https://github.com/TobKra96/music_led_strip_control/wiki/Compatible-Hardware-List#:~:text=You%20will%20need%20at%20least%20500%20MB%20RAM.
