### ISSUE TITLE
Sudden error codes

### ISSUE THREAD

**Issue by DogWater** [TobKra96/music_led_strip_control#22]
I had this up and running rather smoothly for a few hours then all of a sudden it went unresponsive and turned off. I booted up my SSH to reboot and restart the program and it's now throwing error codes and not running at all. I realize I could delete everything and start over to get it to work again- but I'd like to know what went wrong to make sure it wasn't something I did as opposed to a random mishap. Thank you!
![error](https://user-images.githubusercontent.com/69135390/89148038-985e1e80-d526-11ea-97f0-5d872e1064dd.jpg)

**Comment by TobKra96** [comment]
Hi, 

it looks like the programm cannot read the config.json file. At the moment the software do not support multiple webinterface accesses at the same time. It can scramble the config.
Just copy the config.json.bak to config.json and reconfigure the settings. Maybe do a backup after this. :)

Please let me know if it worked for you.

Best regards,
TobKra
