### ISSUE TITLE
What is the use of the resistor?

### ISSUE THREAD

**Issue by NathanDare** [TobKra96/music_led_strip_control#25]
Hi, 

First of all I would just like to say how much I appreciate this project, it is exactly what I wanted to achieve with these LED's 

Regarding the 470 Ohm resistor, what is the difference between that and using a Logic Level Converter? (I am currently using a LLC at the moment) 

I understand that the GPIO pins may only talk at 3.3v and the strip needs a 5v signal, which is the purpose of the LLC but what use does the resistor do on a technical level? I would love to know so I can implement it if necessary 

Do different GPIO pins output signals at different voltages? The guide I followed implemented Pin 18 and used a Logic Level Converter to the LED Strip, Does Pin 21 output at 5v eliminating the need for a LLC? I have tried to find resources to support my hypothesis (guesses at best) but am still unsure 

Any info would very much be appreciated! 
Thanks

**Comment by TobKra96** [comment]
Hi NathanDare,

sorry for the late response.
The Logic Level Converter or Logic Level Shifter pushes the signal voltage from 3,3 to 5v.
A resistor only try to reduce the Ringing of the signal: https://en.wikipedia.org/wiki/Ringing_(signal)
It will reduce the peaks.

The rpi_ws281x library (https://github.com/jgarff/rpi_ws281x) we are using supports different output modes.
PWM, PCM, SPI.
They have different advantages and disadvantages. We are using PWM. It is only available on GPIO pins 12, 18, 40, and 52.
All modes can only output 3,3v as far as I know.

Have a nice day.
TobKra
