### ISSUE TITLE
Can you help me with number 6 can you make a video Mabey 

### ISSUE THREAD

**Issue by rickblij** [TobKra96/music_led_strip_control#35]
Setup microphone Create/edit /etc/asound.conf
sudo nano /etc/asound.conf
Set the file to the following text

pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}
Next, set the USB device to as the default device by editing /usr/share/alsa/alsa.conf

sudo nano /usr/share/alsa/alsa.conf
Change

defaults.ctl.card 0
defaults.pcm.card 0
To

defaults.ctl.card 1
defaults.pcm.card 1

**Comment by TobKra96** [comment]
I made a small video for you:

[![IMAGE ALT TEXT](http://img.youtube.com/vi/d5NjadNNkRE/0.jpg)](https://www.youtube.com/watch?v=d5NjadNNkRE "Microphone configuration MLSC")

Let me know if it helped you.
