### ISSUE TITLE
I can’t get it 

### ISSUE THREAD

**Issue by rickblij** [TobKra96/music_led_strip_control#45]
![image](https://user-images.githubusercontent.com/77531773/105858848-14c04e80-5fec-11eb-8f8b-2d682d8e90db.jpg)
![image](https://user-images.githubusercontent.com/77531773/105858897-27d31e80-5fec-11eb-8088-59e28456ff41.jpg)
How can I fix it

**Comment by TobKra96** [comment]
The default port of webmin is 10000. Please try http://raspberrypi:10000

**Comment by rickblij** [comment]
![image](https://user-images.githubusercontent.com/77531773/105897780-e7d66080-6018-11eb-90aa-6a69ee8e077d.jpg)
Still nothing

**Comment by TobKra96** [comment]
Execute `/etc/init.d/webmin restart`

**Comment by rickblij** [comment]
![image](https://user-images.githubusercontent.com/77531773/105901572-d8a5e180-601d-11eb-8671-fe83e7b2c83e.jpg)
Still nothing

**Comment by rickblij** [comment]
Are you on now mabey you can do it on TeamViewer

**Comment by TobKra96** [comment]
Yes I am online now.  Click on details and accept.

**Comment by rickblij** [comment]
![image](https://user-images.githubusercontent.com/77531773/105902610-2a9b3700-601f-11eb-8531-570ed6068eb6.jpg)
There is nothing

**Comment by TobKra96** [comment]
ok, I can try to take look on it with team viewer.

**Comment by rickblij** [comment]
How can I download that in a raspberry pi

**Comment by rickblij** [comment]
![image](https://user-images.githubusercontent.com/77531773/105904143-0fc9c200-6021-11eb-8e1b-71e71f5205dd.jpg)

**Comment by TobKra96** [comment]
Do you have discord? Here ist the invite link: https://discord.gg/D8pdQpAr

**Comment by TobKra96** [comment]
Topic closed. I tried to help you in discord.
