### ISSUE TITLE
update

### ISSUE THREAD

**Issue by dkcandy** [TobKra96/music_led_strip_control#46]
Hi,

Could you please help how can i upgrade to the latest version?

Thanks

**Comment by TobKra96** [comment]
Hi,

you have to reset the local changes of the checkout repository and pull the newest changes:

Go inside your repository folder on the raspberry pi (with e.g. cd `/share/music_led_strip_control`)
`sudo git fetch --all`
`sudo git reset --hard origin/master`
`sudo git pull origin master`

After this, you can start with the configuration: https://github.com/TobKra96/music_led_strip_control/wiki/Installation-Guide#iv-configure-music-led-strip-control

**Comment by dkcandy** [comment]
it works perfectly, thank you very much for your work

**Comment by TobKra96** [comment]
Have fun with the project. :smiley:
