### ISSUE TITLE
Client doesn't work in Firefox

### ISSUE THREAD

**Issue by paulheald** [TobKra96/music_led_strip_control#50]
When you save the settings for the device in Firefox, the browser rejects it with NS_BINDING_ABORTED. I looked at this quickly, I think it's because the page reloads faster than the post to the rest endpoint, but I'm not 100% sure. It works for me in Chrome with no issues.

**Comment by TobKra96** [comment]
Hi, thanks for the debugging. 👍 I will try to fix it this evening.

**Comment by paulheald** [comment]
Great! I also noticed it does the same on FF on iOS. Let me know if I can help. I have only just started digging into the code. Loving this project! :)

**Comment by TobKra96** [comment]
Hi, I think you saw the right problem. The Websites reloads before the ajax requests were finished.
Now the reload should wait until all requests are sent.
Let me know if you see any more problems.

Have a great day.

**Comment by paulheald** [comment]
Pulled and it works perfectly on both phone and desktop. Thank you!
