### ISSUE TITLE
Add a dropdown menu in Device Settings, to select between RGB/GRB strips

### ISSUE THREAD

**Issue by Teraskull** [TobKra96/music_led_strip_control#52]
When I select the `Red` color preset, the strip lights green, and vice versa.

As an option, a toggle can be added to the Device Settings, to select between RGB/GRB strips.
But then the color presets have to be refactored, because they are hard-coded right now.

**Comment by TobKra96** [comment]
Hi, do you use the esp client or the direct output via raspberry pi?

**Raspberry Pi Output**
With the raspberry pi. You can set the following setting in the file:
https://github.com/TobKra96/music_led_strip_control/blob/master/server/libs/outputs/output_raspi.py

In line 33. Between `self.channel = ws.ws2811_channel_get(self._leds, 0)` and `ws.ws2811_channel_t_count_set(self.channel, self._led_count)`

```
#LED_STRIP      = ws.WS2811_STRIP_RGB
LED_STRIP      = ws.WS2811_STRIP_GBR
#LED_STRIP      = ws.SK6812_STRIP_RGBW
#LED_STRIP      = ws.SK6812W_STRIP

ws.ws2811_channel_t_strip_type_set(channel, LED_STRIP)
```

**ESP Output**
For esp you have to change the following in the file: https://github.com/TobKra96/music_led_strip_control/blob/master/client/udp/esp/nodemcu_client/nodemcu_client.ino

Line 23: `NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod> ledstrip(NUM_LEDS, PixelPin);`
Change NeoGrbFeature to the wanted output type:
https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object
NeoGrbFeature
NeoGrbwFeature
NeoRgbFeature
NeoRgbwFeature
NeoBrgFeature
NeoRbgFeature

Let me know if it worked for you. I will add a selection of the Strip Types in the next version.
Have a great day :)

**Comment by Teraskull** [comment]
I only used one Raspberry Pi 3B+ for both server and client. I will check if changing the output helps, thanks.

**Comment by Teraskull** [comment]
Thanks, the proposed code works:

```python
LED_STRIP = ws.WS2811_STRIP_GBR
ws.ws2811_channel_t_strip_type_set(self.channel, LED_STRIP)
```

It's then really easy to add a similar toggle to the settings, like the `Used Output Type` dropdown.

**Comment by TobKra96** [comment]
Yes, that's the plan. I will implement it after the pull request is done :)
Have a great day!

**Comment by TobKra96** [comment]
Added Dropdown for Raspberry pi Output:
![image](https://user-images.githubusercontent.com/7833146/107874943-665a4b80-6ebd-11eb-85a7-6b62dec00841.png)

I accidentally used the master. Sorry

**Comment by Teraskull** [comment]
No problem. It is missing the `ws.WS2812_STRIP`, which is the default GRB WS2812B Strip.

**Comment by TobKra96** [comment]
Fixed it: 
![image](https://user-images.githubusercontent.com/7833146/107875779-2053b680-6ec2-11eb-9ee3-9250462d3152.png)

**Comment by Teraskull** [comment]
Great, we can close this now.
