### ISSUE TITLE
New logo propositions

### ISSUE THREAD

**Issue by Teraskull** [TobKra96/music_led_strip_control#57]

**Comment by Teraskull** [comment]
## Spectrum Logo

Option 1:
![mlsc_logo_banner-01](https://user-images.githubusercontent.com/24798198/107284302-e0be4200-6a5d-11eb-81f1-828c5ad56e9f.png)

Option 2:
![mlsc_logo_banner-02](https://user-images.githubusercontent.com/24798198/107284460-2aa72800-6a5e-11eb-9d46-c9638bac12dc.png)

**Comment by TobKra96** [comment]
Hi,

the logos look very good. They are elegant and discreet.
My favorites are the ones with the bold font. Spectrum Logo 1 and LED Strip Logo 2.

Some ideas:
- Maybe you can increase the a little bit the saturation. I think you manually decreased it.
- I see the Topics, that the two different logos should address. 
Spectrum -> Music 
LED Strip -> LED Strip / RGB / Technical
I would love it if there is a way to combine two topics inside one logo.
- Maybe we will need an inverted color logo for the sidebar inside the web interface.

Great work. 👍 
Have a nice day!

**Comment by Teraskull** [comment]
The colors are from a pastel palette. I can try with a brighter one.

I will experiment with combining them.

I think instead of inverting, a white background would be better.

**Comment by Teraskull** [comment]
## Rainbow Spectrum

Light Background:
![mlsc_logo_rainbow_01](https://user-images.githubusercontent.com/24798198/107448151-58b16880-6b41-11eb-9d16-719d3c5b59e4.png)


Dark Background:
![mlsc_logo_rainbow_02](https://user-images.githubusercontent.com/24798198/107448196-6c5ccf00-6b41-11eb-9e1c-f588bd1e95da.png)


This logo includes the three RGB colors, the rainbow also represents the Wi-Fi signal, which has a reflection under it, that is an audio spectrum. The logo looks great both on light and dark backgrounds, specifically here is the dark color from the web interface.

In my opinion, it is the best one from all three options.

**Comment by TobKra96** [comment]
Good idea.
I am not sure if someone who does not know the idea of the wifi would interpret the rainbow as a wifi signal.
Mhh, If would think about the MLSC, my first thought would be music and led. 

What do you think about these ones:

### Spectrum LED Combined

![SpectrumLEDComb](https://user-images.githubusercontent.com/7833146/107516785-30f7ea00-6bad-11eb-96a8-aaf1c34e3500.png)
![SpectrumLEDComb_white](https://user-images.githubusercontent.com/7833146/107516787-31908080-6bad-11eb-9d58-37e3ae326f34.png)

This is the mix between the Spectrum and the LED technical logo.

**Comment by Teraskull** [comment]
There are too many LEDs, with a lot of detail, what if you change the LEDs to simple circles, like under the rainbow? I wil try that.

**Comment by Teraskull** [comment]
## LED Spectrum

Light Background:
![mlsc_logo_2-01-01](https://user-images.githubusercontent.com/24798198/107544606-b1791380-6bca-11eb-902c-09440178e380.png)


Dark Background:
![mlsc_logo_2-02-01](https://user-images.githubusercontent.com/24798198/107544608-b2aa4080-6bca-11eb-8ad6-bb7f25580f28.png)


This option is cleaner, and the top "M" is more visible.

In my opinion, this logo, or the Rainbow will be the best looking on the web interface.


The Rainbow logo is less wide, and is possible to put it to the left of "MLSC".

## Rainbow Spectrum Asymmetric

Light Background:
![mlsc_logo_2-01-01-01](https://user-images.githubusercontent.com/24798198/107545665-d621bb00-6bcb-11eb-9624-8a1a7e684d4c.png)


Dark Background:
![mlsc_logo_2-02-01-01](https://user-images.githubusercontent.com/24798198/107545663-d4f08e00-6bcb-11eb-9fa0-cf8976ee0eac.png)

**Comment by TobKra96** [comment]
Hi,

my favorite at the moment is your LED Spectrum. Yes, the LEDs in my attempt are too detailed and the "m" is a little bit edgy.
These are the colors of the Webinterface.
```
.blue {
  color: #3498DB; }

.purple {
  color: #9B59B6; }

.green {
  color: #1ABB9C; }

.aero {
  color: #9CC2CB; }

.red {
  color: #E74C3C; }

.dark {
  color: #34495E; }

```
The typical font color is #73879c

Some additional colors:
orange: #F39C12
sky blue: #50C1CF

Could you prepare the LED Spectrum with these colors?
What do you mean?

Have a great day!

**Comment by Teraskull** [comment]
Maybe we should also consider the width,like in the rainbow logo? On the top of the web interface, the logo is left to the text, and the LED Spectrum is too long to look good on the left.

What do you think?

**Comment by Teraskull** [comment]
## LED Spectrum Left Aligned

Light Background:
![mlsc_logo_2-01-01-01-01](https://user-images.githubusercontent.com/24798198/107556756-19cef180-6bd9-11eb-9c62-8d84ba33baf3.png)

Dark Background:
![mlsc_logo_2-02-01-01-01](https://user-images.githubusercontent.com/24798198/107556751-19365b00-6bd9-11eb-947b-f665e0c20c40.png)


As you can see, the width is to big to be placed on the top corner on the web interface.

Also, the purple and red colors do not go well with the dark background.

I think the "M" on the logo looks nice, but it does not match the overall text font.

**Comment by TobKra96** [comment]
Yes, the purple does not match. 
And yes it's too big for the horizontal order.

Another idea:
### Volume Meter
![Vumeter](https://user-images.githubusercontent.com/7833146/107558502-25bbb300-6bdb-11eb-8f99-7d2b30a2ec11.png)

**Comment by Teraskull** [comment]
I am checking out your option now

**Comment by BomBastikDE** [comment]
LED Strip Logo is nice

**Comment by Teraskull** [comment]
I tested the LED Strip Logo and it is also quite detailed, the LED legs are small, and not visible when zoomed out.

I tried flipping the Rainbow upside down, but now it looks like a Hanukkah menorah holder. Your last Rainbow idea is nice, but the spectrum does not make sense when there are multiple colors in the same bar.

I think the Rainbow Spectrum Asymmetric Logo is the cleanest, and looks good when zoomed out. Forget about the Wi-Fi part, it's just the 3 main RGB colors with a reflecting spectrum. It also uses only 3 colors that look good on the dark background, unlike the LED Spectrum, which has 6, and gets detailed.

**Comment by TobKra96** [comment]
Ok, understand.

Let's choose the Rainbow Spectrum Asymmetric with horizontal order.
Can we try one last thing? I like the green and red of the logo, but I think the blue-purple does not fit inside the webinterface.

![image](https://user-images.githubusercontent.com/7833146/107572395-856e8a00-6bec-11eb-874d-32f7cf807067.png)

Can you try to use the typical font color: 73879c
or the blue: 3498DB

**Comment by Teraskull** [comment]
Great, your Blue color looks perfect on the dark background!

## Rainbow Spectrum Asymmetric

![mlsc_logo_2-01-01-01-01-01](https://user-images.githubusercontent.com/24798198/107574531-1d6d7300-6bef-11eb-8d7f-83c42a5784d2.png)
![mlsc_logo_2-02-01-01-01-01](https://user-images.githubusercontent.com/24798198/107574537-1e060980-6bef-11eb-9214-141f9ae85a3e.png)

How can I send you the high-resolution PNGs with both separate logo and text?

**Comment by TobKra96** [comment]
Perfect!
![image](https://user-images.githubusercontent.com/7833146/107575539-480bfb80-6bf0-11eb-8a23-1c059d31f8a6.png)

Can you zip everything together and upload it here inside the issue? Or you can join the discord server and upload the files there? https://discord.gg/bMmWYGcz
Maybe you can provide 
- the original project file
- a vector file
- two high res png with background 
- one without background?

Great work!
Have a nice day!

**Comment by Teraskull** [comment]
Of course I can, one moment, I will tidy up the exports a bit.

**Comment by Teraskull** [comment]
Rainbow Spectrum Asymmetric selected as a logo. Issue closed.
