### ISSUE TITLE
Reduce the size of the JS vendor libraries

### ISSUE THREAD

**Issue by Teraskull** [TobKra96/music_led_strip_control#58]
Right now the total size of the vendor libraries is around `100mb` That's too much for a simple Bootstrap Admin Panel. We can reduce that size by removing the unnecessary `src` files, since we do not need to build the libraries manually. Also, I believe there are some unused libraries that can be safely removed.

Of course this should go with a lot of testing, to make sure we don't break any dependencies.

**Comment by TobKra96** [comment]
Do you think, we can close this topic?

**Comment by Teraskull** [comment]
Sure.
