### ISSUE TITLE
add an wiki to update the system

### ISSUE THREAD

**Issue by BomBastikDE** [TobKra96/music_led_strip_control#62]
you develop a lot of thinks - could you add an chapter with points we have to do to update the system?

Thanks for your work

**Comment by Teraskull** [comment]
Just rerun the automated installation again:

```bash
curl -sSL https://raw.githubusercontent.com/TobKra96/music_led_strip_control/master/setup.sh | sudo bash
```

It will automatically save the previous version as a backup, download the new version, and restore your config.

Then, if you use the autostart, restart the service with:

```bash
sudo systemctl restart mlsc.service
```

It should be updated now.

**Comment by TobKra96** [comment]
I will add an updated chapter to the wiki tomorrow. 👍

**Comment by TobKra96** [comment]
Update Page added to the wiki. [Update Guide](https://github.com/TobKra96/music_led_strip_control/wiki/Update-Guide)
Have a great day!
