### ISSUE TITLE
Update mobile device preview inside readme

### ISSUE THREAD

**Issue by TobKra96** [TobKra96/music_led_strip_control#63]
We have to update the mobile device view inside the readme.
Additionally, the link is wrong.

Can you update it with the new logo? @Teraskull
Maybe we can cut the background too?

![](https://user-images.githubusercontent.com/24798198/107167989-ae0f3d80-69ba-11eb-8d5c-aceaec15d054.png)

**Comment by Teraskull** [comment]
Sure, will do that today.

**Comment by Teraskull** [comment]
I wouldn't cut the background, because the laptop edges will mix with the background on dark mode.

**Comment by TobKra96** [comment]
Ok 👍, that's right.

**Comment by TobKra96** [comment]
Finished with https://github.com/TobKra96/music_led_strip_control/commit/61e144fefa13469ab9df473982739d52a5087a39
