### ISSUE TITLE
Purple and pink color

### ISSUE THREAD

**Issue by vanagsgirts** [TobKra96/music_led_strip_control#68]
Hi,
Default pink and purple colors are exactly the same. How to adjust color for default purple?

**Comment by TobKra96** [comment]
Hi, you can find the color definitions inside the config file, it should be located in `/share/.mlsc/config.py`Please ensure mlsc is not running, if you try to change the config. `sudo systemctl stop mlsc` You can try to find your perfect color code with the single effect and the custom color option.

**Comment by vanagsgirts** [comment]
Thank you! Found it and adjusted.
