### ISSUE TITLE
MLSC Server without LAN-Connection

### ISSUE THREAD

**Issue by BomBastikDE** [TobKra96/music_led_strip_control#81]
actuell I install the MLSC Server as it is explane in the WIKI.
Actuell the MLSC Server starts without LAN connection and I can see the Webside - but the Clients doesn't connect - after Plug in LAN an reboot, everything works well.
Can help someone to confige the system, so I can use it Mobile without LAN?

Best regards

**Comment by TobKra96** [comment]
Hi,
I will build the setup as you described and give you feedback tomorrow.
Have a nice day!
TobKra

**Comment by TobKra96** [comment]
Hi, I could reproduce the issue.
So I started the Raspberry Pi without Ethernet, only Wifi.
The Wifi Network was not fast enough for the program and the socket was not valid.
Now it will refresh the socket if it is not valid.

Please update your program with 
`curl -sSL https://raw.githubusercontent.com/TobKra96/music_led_strip_control/master/setup.sh | sudo bash`
and send me a short feedback message, if the fix worked for you.

Have a nice day!
TobKra

**Comment by BomBastikDE** [comment]
....it works after update!

Thanks all lot - for this Projekt

**Comment by TobKra96** [comment]
You are welcome :)
