### ISSUE TITLE
LED stays off

### ISSUE THREAD

**Issue by Jonas1403** [TobKra96/music_led_strip_control#82]
Hi all,
really nice project.
I am trying to build the setup with the esp8266 but actually it fails.
The led does not light up.
My suspicion is that the data connection from esp to led cable is broken.
I already measured the voltage that the led cable gets and it fits (round about 5v).
Is it possible to measure the data connection or if data is transmitted?

My esp8266 is use is this:
https://www.azde.ly/8541f9d8a8470612eaa6 (page 16)
I already tried it with the D3 and RX pin, both fails.

I also tried this NeoPixelBus test and it also fails: https://github.com/Makuna/NeoPixelBus/blob/master/examples/NeoPixelTest/NeoPixelTest.ino

Do you have an idea what i am doing wrong?

![IMG_20210226_095643](https://user-images.githubusercontent.com/24855857/109280136-ed42e880-781a-11eb-83d6-3fc5141d94e4.jpg)
![IMG_20210226_095705](https://user-images.githubusercontent.com/24855857/109280162-f633ba00-781a-11eb-8f8a-57b696a30e98.jpg)
<img width="1270" alt="Bildschirmfoto 2021-02-26 um 10 07 08" src="https://user-images.githubusercontent.com/24855857/109280178-f9c74100-781a-11eb-9603-6c7db9f8ecc7.png">

**Comment by TobKra96** [comment]
Hi,

neobus will use spi for the data signal, so we will need the RX pin.
Does the RX pin look like not soldered on the top? Please ensure it is.
As far as I can see, you bridged your fuse?
Have you tried to adjust the Poti?
Where did you measure the 5V? Directly at the LED strip?
Have you checked, you are using the Di pin?

I think it is only for the picture, but you have to be careful running this on your power supply. The housing of the ps is grounded and could cause a short circuit.

Have a nice day.
TobKra

**Comment by Jonas1403** [comment]
Hi TobKra,

you are absolutely right. I did not solder the RX pin 🤦🏼‍♂️. 
What a stupid mistake. Now it seems that all works fine.

Thanks for your help and for this fantastic project.
