### ISSUE TITLE
Signal losing

### ISSUE THREAD

**Issue by d0uble-b** [TobKra96/music_led_strip_control#85]
Hi, its me again.
I have another issue now.
When i switch between the music effects, the signal is freezing a bit or stopping and the strip not will be synchronised anymore with the music beat. When i stop the music, the effects are playing the last 6-7 beats of the music. 
How could i fix it?

**Comment by TobKra96** [comment]
Hi,
can you check the CPU usage of your raspberry pi with `htop`?
Maybe there is a untervolting of the raspberry pi?
How big is your power supply of the raspberry and how long is the usb cable?

With some mics, you have to play around with the buffer size and the sample rate of the mic.

Have a great day!
TobKra
