### ISSUE TITLE
Speed slider in Sync Fade effect does not do anything

### ISSUE THREAD

**Issue by Teraskull** [TobKra96/music_led_strip_control#95]
It also does not show saved value, it's always 1.
Is it required there?

**Comment by TobKra96** [comment]
Maybe a bug, it should update and change the speed.

**Comment by TobKra96** [comment]
Should work. Please check it again.

**Comment by Teraskull** [comment]
Still not working. Speed value is not getting imported from config.

**Comment by TobKra96** [comment]
Mhh I cannot reproduce it.
I change this setting: 
![image](https://user-images.githubusercontent.com/7833146/112757877-d5ae7980-8feb-11eb-93bf-ee3a2a03c269.png)
Save, Restart the Program and it is still on 10.1.

**Comment by Teraskull** [comment]
Problem was on my end, I probably had a broken config. Reset to default config, and it works now. Issue closed.
