### ISSUE TITLE
Invert LED Setting do not save

### ISSUE THREAD

**Issue by TobKra96** [TobKra96/music_led_strip_control#97]
The Invert LED inside the device view does not save correctly.

**Comment by TobKra96** [comment]
I could not reproduce the error.

**Comment by Teraskull** [comment]
1. Have an existing device with "Invert LED" off.
2. Create a new device, which has "Invert LED" on by default.
3. Toggle between existing device and new device.
4. You should see that "Invert LED" is not in the same state each time.

**Comment by Teraskull** [comment]
Fixed with 51d3d66bae5af8a6941b2ea01f351e2a2d0395f4.
