### ISSUE TITLE
main.py run error

### ISSUE THREAD

**Issue by eobidi** [TobKra96/music_led_strip_control#99]
I have a problem... my fist ok.. but error this time.
![1](https://user-images.githubusercontent.com/33429246/112718938-b4388980-8f28-11eb-8d3d-b62a3d7fac0b.png)

**Comment by eobidi** [comment]
OK.. Fixed

**Comment by TobKra96** [comment]
Hi,
an update should help.
See https://github.com/TobKra96/music_led_strip_control/wiki/Update-Guide

**Comment by TobKra96** [comment]
Fixed with commit: https://github.com/TobKra96/music_led_strip_control/commit/6ea0b08967c71e2f23ae1971f53409d88a166c56
